version: "3.9"
services:
  migration_postgres:
    image: postgres:15
    container_name: migration_postgres
    volumes:
      - ~/.pg/pg_data/migration:/var/lib/postgresql/data
    env_file:
      - .env
  migration_django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migration_django
    depends_on:
      - migration_postgres
    volumes:
      - static_volume:/migration/static
      - media_volume:/migration/media
    env_file:
      - .env
    command: >
      bash -c "./manage.py migrate && gunicorn -b 0.0.0.0:8000 djangomigration.wsgi:application"
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: migration_nginx
    image: migration_nginx
    volumes:
      - static_volume:/migration/static
      - media_volume:/migration/media
    depends_on:
      - migration_django
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"
volumes:
  static_volume:
  media_volume:
